# Generated by Django 5.2.14 on 2026-05-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('TIME_UP', 'Time Up')], default='IDLE', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_time', models.PositiveIntegerField(default=0, help_text='Stored remaining seconds checkpoint')),
                ('time_up_started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer_state', to='sess.session')),
            ],
        ),
    ]
